[Tools]
; Cambia a False para deshabilitar cada tool

Media_Missing_Frames = True
Reload_All_Reads = True
Rename_Writes_From_Reads = True
FR_Read_to_FrameRange = True
FR_Read_to_Write = True
FR_TimeClip_to_Write = True
Paste_To_Selected = True
Copy_with_inputs = True
Paste_with_inputs = True
Duplicate_with_inputs = True
DasGrain_Kronos_Comp = True
AnimationMaker = True
MultiKnobEdit = True
Default_KnobDefaults = True
OCIOFileTransform_IP = True
CDL_CC_IP = True
Perf_Time = True
Shortcut_Editor = True
