[Tools]
; Cambia a True para habilitar cada tool. Default: False para testear una por vez.
Media_Missing_Frames = True
Reload_All_Reads = False
Rename_Writes_From_Reads = False
FR_Read_to_FrameRange = False
FR_Read_to_Write = False
FR_TimeClip_to_Write = False
DasGrain_Kronos_Comp = False
AnimationMaker = False
MultiKnobEdit = False
Default_KnobDefaults = False
OCIOFileTransform_IP = False
CDL_CC_IP = False
Perf_Time = False
Shortcut_Editor = False
