"""
________________________________________

  LGA_UpdateFolderFavs v1.00 | Lega
  Actualiza los favoritos de carpetas
________________________________________

"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import shlex
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import nuke  # type: ignore
except ImportError:
    nuke = None

try:
    from LGA_QtAdapter_ToolPackB import QtWidgets, QtGui, QtCore, primary_screen_geometry

    QWidget = QtWidgets.QWidget
    QVBoxLayout = QtWidgets.QVBoxLayout
    QHBoxLayout = QtWidgets.QHBoxLayout
    QTableWidget = QtWidgets.QTableWidget
    QTableWidgetItem = QtWidgets.QTableWidgetItem
    QHeaderView = QtWidgets.QHeaderView
    QLabel = QtWidgets.QLabel
    QPushButton = QtWidgets.QPushButton
    QApplication = QtWidgets.QApplication
    QAbstractItemView = QtWidgets.QAbstractItemView
    QStyle = QtWidgets.QStyle
    QStyledItemDelegate = QtWidgets.QStyledItemDelegate
    QPalette = QtGui.QPalette
    QFont = QtGui.QFont
    QColor = QtGui.QColor
    Qt = QtCore.Qt
    QT_AVAILABLE = True
except Exception:
    QtWidgets = QtGui = QtCore = None
    QWidget = object
    QVBoxLayout = QHBoxLayout = QTableWidget = QTableWidgetItem = None
    QHeaderView = QLabel = QPushButton = QApplication = None
    QAbstractItemView = QStyle = QStyledItemDelegate = None
    QPalette = QFont = QColor = Qt = None
    QT_AVAILABLE = False


PREF_FILENAME = "FileChooser_Favorites.pref"
HEADER_LINE = "# Do not edit this file, it is automatically generated by NukeStudio."
FOOTER_LINE = "# End of generated file."
MANAGED_FLAGS = (
    "-image",
    "-script",
    "-project",
    "-python",
    "-font",
    "-geo",
    "-misc",
    "-sequence",
)


@dataclass(frozen=True)
class FavoriteEntry:
    flags: tuple[str, ...]
    label: str
    display_label: str
    shortcut: str
    path: str
    raw_line: str


@dataclass(frozen=True)
class PlatformConfig:
    name: str
    desktop_path: Path
    t_root_path: Path


@dataclass(frozen=True)
class ChangeRow:
    action: str
    name: str
    current_path: str
    new_path: str


if QT_AVAILABLE:
    class ColorMixDelegate(QStyledItemDelegate):
        def __init__(self, table_widget, background_colors, mix_color=(88, 88, 88), parent=None):
            super(ColorMixDelegate, self).__init__(parent)
            self.table_widget = table_widget
            self.background_colors = background_colors
            self.mix_color = mix_color

        def paint(self, painter, option, index):
            row = index.row()
            column = index.column()
            if row < len(self.background_colors) and column < len(self.background_colors[row]):
                if option.state & QStyle.State_Selected:
                    original_color = QColor(self.background_colors[row][column])
                    mixed_color = self.mix_colors(
                        (original_color.red(), original_color.green(), original_color.blue()),
                        self.mix_color,
                    )
                    option.palette.setColor(QPalette.Highlight, QColor(*mixed_color))
                else:
                    original_color = QColor(self.background_colors[row][column])
                    option.palette.setColor(QPalette.Base, original_color)
            super(ColorMixDelegate, self).paint(painter, option, index)

        def mix_colors(self, original_color, mix_color):
            r1, g1, b1 = original_color
            r2, g2, b2 = mix_color
            return ((r1 + r2) // 2, (g1 + g2) // 2, (b1 + b2) // 2)


    class UpdateFolderFavsWindow(QWidget):
        def __init__(
            self,
            config: PlatformConfig,
            rows: list[ChangeRow],
            current_entries: list[FavoriteEntry],
            new_entries: list[FavoriteEntry],
            pref_path: Path,
            parent=None,
        ):
            super(UpdateFolderFavsWindow, self).__init__(parent)
            self.config = config
            self.rows = rows
            self.current_entries = current_entries
            self.new_entries = new_entries
            self.pref_path = pref_path
            self.row_background_colors: list[list[str]] = []
            self.applied = False
            self._init_ui()
            self._populate_rows()
            self.adjust_window_size()

        def _init_ui(self):
            self.setWindowTitle("Update Folder Favs")
            layout = QVBoxLayout(self)

            self.table = QTableWidget(0, 4, self)
            self.table.setHorizontalHeaderLabels(["Action", "Favorite", "Current Path", "New Path"])
            self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
            self.table.horizontalHeader().setStretchLastSection(True)
            self.table.setSelectionBehavior(QTableWidget.SelectRows)
            self.table.setSelectionMode(QAbstractItemView.SingleSelection)
            self.table.verticalHeader().setVisible(False)
            self.table.setAlternatingRowColors(False)
            self.table.setWordWrap(False)
            self.table.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)

            font = QFont()
            font.setBold(True)
            self.table.horizontalHeader().setFont(font)

            delegate = ColorMixDelegate(self.table, self.row_background_colors)
            self.table.setItemDelegate(delegate)
            layout.addWidget(self.table)

            button_layout = QHBoxLayout()
            button_layout.addStretch()

            self.apply_button = QPushButton("Apply", self)
            self.apply_button.setCursor(Qt.PointingHandCursor)
            self.apply_button.setStyleSheet(
                "QPushButton { padding: 6px 14px; font-weight: bold; background-color: #3e5a37; color: white; border: 0px; }"
                "QPushButton:hover { background-color: #4a6a42; }"
            )
            self.apply_button.clicked.connect(self._apply_changes)

            self.cancel_button = QPushButton("Cancel", self)
            self.cancel_button.setCursor(Qt.PointingHandCursor)
            self.cancel_button.setStyleSheet(
                "QPushButton { padding: 6px 14px; font-weight: bold; background-color: #5f5f5f; color: white; border: 0px; }"
                "QPushButton:hover { background-color: #787878; }"
            )
            self.cancel_button.clicked.connect(self.close)

            button_layout.addWidget(self.apply_button)
            button_layout.addWidget(self.cancel_button)
            layout.addLayout(button_layout)
            self.setLayout(layout)

        def _populate_rows(self):
            if not self.rows:
                self.rows = [ChangeRow("Keep", "No changes", "", "Managed favorites are already up to date")]

            for row_data in self.rows:
                row = self.table.rowCount()
                self.table.insertRow(row)

                action_item = QTableWidgetItem(row_data.action)
                favorite_item = QTableWidgetItem(row_data.name)
                current_item = QTableWidgetItem(row_data.current_path or "-")
                new_item = QTableWidgetItem(row_data.new_path or "-")

                for item in (action_item, favorite_item, current_item, new_item):
                    item.setFlags(item.flags() & ~Qt.ItemIsEditable)

                action_color = self._action_color(row_data.action)
                action_item.setTextAlignment(Qt.AlignCenter)
                action_item.setBackground(QColor(action_color))
                action_item.setForeground(QColor(self._text_color_for_bg(QColor(action_color))))

                self.table.setItem(row, 0, action_item)
                self.table.setItem(row, 1, favorite_item)
                self.table.setItem(row, 2, current_item)
                self.table.setItem(row, 3, new_item)

                neutral = "#8a8a8a"
                self.row_background_colors.append([action_color, neutral, neutral, neutral])

            self.table.resizeColumnsToContents()

        def _action_color(self, action: str) -> str:
            colors = {"Add": "#47633f", "Remove": "#6b4747", "Update": "#7b6546", "Keep": "#4d4d4d"}
            return colors.get(action, "#4d4d4d")

        def _text_color_for_bg(self, color: QColor) -> str:
            return "#cccccc"

        def _apply_changes(self):
            try:
                _, _, final_entries, _, _, _, backup_path = execute_update(
                    pref_path=self.pref_path,
                    dry_run=False,
                )
            except Exception as exc:
                if nuke:
                    nuke.message(f"Update Folder Favs\n\nNo se pudieron aplicar los cambios:\n{exc}")
                else:
                    print(f"ERROR: {exc}")
                return

            self.applied = True
            result_lines = ["Favoritos actualizados correctamente."]
            if backup_path:
                result_lines.extend(["", f"Backup: {backup_path}"])
            result_lines.extend(["", "Favoritos finales:"])
            result_lines.extend(summarize_entries(final_entries))

            if nuke:
                nuke.message("\n".join(result_lines))
            else:
                print("\n".join(result_lines))
            self.close()

        def adjust_window_size(self):
            self.table.resizeColumnsToContents()
            width = self.table.verticalHeader().width() + 40
            for i in range(self.table.columnCount()):
                width += self.table.columnWidth(i) + 20

            header_height = self.table.horizontalHeader().height()
            button_height = max(self.apply_button.sizeHint().height(), self.cancel_button.sizeHint().height())
            frame_height = self.table.frameWidth() * 2
            row_heights = sum(self.table.rowHeight(i) for i in range(self.table.rowCount()))
            scrollbar_height = self.table.horizontalScrollBar().sizeHint().height()
            table_height = header_height + row_heights + frame_height + 2
            if self.table.horizontalScrollBar().isVisible():
                table_height += scrollbar_height
            self.table.setFixedHeight(table_height)

            layout_spacing = self.layout().spacing() * 2
            margins = self.layout().contentsMargins()
            margins_height = margins.top() + margins.bottom()
            height = table_height + button_height + layout_spacing + margins_height + 12

            screen_rect = primary_screen_geometry()
            final_width = min(width, int(screen_rect.width() * 0.85))
            final_height = min(height, int(screen_rect.height() * 0.85))
            self.resize(final_width, final_height)
            self.move(
                screen_rect.x() + (screen_rect.width() - final_width) // 2,
                screen_rect.y() + (screen_rect.height() - final_height) // 2,
            )


def detect_platform_config(platform_name: str | None = None) -> PlatformConfig:
    system_name = (platform_name or platform.system()).lower()
    home = Path.home()

    if system_name.startswith("win"):
        return PlatformConfig(
            name="windows",
            desktop_path=home / "Desktop",
            t_root_path=Path("T:/"),
        )

    if system_name in {"darwin", "mac", "macos"}:
        return PlatformConfig(
            name="mac",
            desktop_path=home / "Desktop",
            t_root_path=Path("/Volumes/T Viaja/T"),
        )

    raise RuntimeError(f"Sistema no soportado: {platform_name or platform.system()}")


def normalize_path_string(value: str) -> str:
    path = value.strip().strip('"').replace("\\", "/")

    if path.startswith("T:/"):
        prefix = "T:/"
        rest = path[3:]
        while "//" in rest:
            rest = rest.replace("//", "/")
        if rest.endswith("/") and rest != "/":
            rest = rest.rstrip("/")
        return prefix + rest

    while "//" in path:
        path = path.replace("//", "/")
    if path.endswith("/") and path != "/":
        path = path.rstrip("/")
    return path


def render_token(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def favorite_line(entry: FavoriteEntry) -> str:
    parts = ["add_favorite_dir"]
    parts.extend(entry.flags)
    parts.append(render_token(entry.label))
    parts.append(render_token(entry.display_label))
    parts.append(render_token(entry.shortcut))
    parts.append(render_token(entry.path))
    return " ".join(parts)


def parse_favorite_line(line: str) -> FavoriteEntry | None:
    stripped = line.strip()
    if not stripped.startswith("add_favorite_dir "):
        return None

    try:
        tokens = shlex.split(stripped, posix=True)
    except ValueError:
        return None

    if len(tokens) < 5 or tokens[0] != "add_favorite_dir":
        return None

    payload = tokens[1:]
    index = 0
    flags: list[str] = []
    while index < len(payload) and payload[index].startswith("-"):
        flags.append(payload[index])
        index += 1

    if len(payload) - index < 4:
        return None

    label, display_label, shortcut, path = payload[index : index + 4]
    return FavoriteEntry(
        flags=tuple(flags),
        label=label,
        display_label=display_label,
        shortcut=shortcut,
        path=normalize_path_string(path),
        raw_line=line.rstrip("\n"),
    )


def build_managed_entries(config: PlatformConfig) -> list[FavoriteEntry]:
    entries = [
        FavoriteEntry(MANAGED_FLAGS, "Desktop", "Desktop", "", normalize_path_string(str(config.desktop_path)), ""),
        FavoriteEntry(MANAGED_FLAGS, "T:", "T:", "", normalize_path_string(str(config.t_root_path)), ""),
    ]

    vfx_names = sorted(
        [child.name for child in config.t_root_path.iterdir() if child.is_dir() and child.name.startswith("VFX-")],
        key=str.lower,
    )

    for name in vfx_names:
        entries.append(
            FavoriteEntry(
                MANAGED_FLAGS,
                name,
                name,
                "",
                normalize_path_string(str(config.t_root_path / name)),
                "",
            )
        )

    return entries


def managed_roots(config: PlatformConfig) -> tuple[str, str]:
    return normalize_path_string(str(config.desktop_path)), normalize_path_string(str(config.t_root_path))


def is_managed_entry(entry: FavoriteEntry, config: PlatformConfig) -> bool:
    desktop, t_root = managed_roots(config)
    entry_path = normalize_path_string(entry.path)

    if entry.label in {"Desktop", "Desktop Mac"} or entry_path == desktop:
        return True
    if entry.label in {"T:", "T", "T Mac"} or entry_path == t_root:
        return True
    if entry.label.startswith("VFX-"):
        return True
    if entry_path.startswith(t_root + "/") and Path(entry_path).name.startswith("VFX-"):
        return True
    if entry_path.startswith("/../Volumes/") and Path(entry_path).name.startswith("VFX-"):
        return True
    return False


def read_pref_lines(pref_path: Path) -> list[str]:
    if not pref_path.exists():
        return [HEADER_LINE + "\n", "\n", FOOTER_LINE + "\n"]
    return pref_path.read_text(encoding="utf-8").splitlines(keepends=True)


def build_updated_lines(pref_path: Path, config: PlatformConfig) -> tuple[list[str], list[FavoriteEntry], list[FavoriteEntry]]:
    original_lines = read_pref_lines(pref_path)
    kept_lines: list[str] = []
    removed_entries: list[FavoriteEntry] = []

    for line in original_lines:
        entry = parse_favorite_line(line)
        if entry and is_managed_entry(entry, config):
            removed_entries.append(entry)
            continue
        kept_lines.append(line)

    managed_entries = build_managed_entries(config)
    generated_lines = [favorite_line(entry) + "\n" for entry in managed_entries]
    header_lines = [line for line in kept_lines if line.startswith("#")]
    other_lines = [line for line in kept_lines if not line.startswith("#")]

    has_header = any(line.strip() == HEADER_LINE for line in header_lines)
    new_lines: list[str] = []

    if has_header:
        for line in header_lines:
            if line.strip() != FOOTER_LINE:
                new_lines.append(line)
    else:
        new_lines.append(HEADER_LINE + "\n")
        new_lines.append("\n")

    if other_lines:
        new_lines.extend(other_lines)
        if new_lines[-1].strip():
            new_lines.append("\n")

    new_lines.extend(generated_lines)
    if new_lines[-1].strip():
        new_lines.append("\n")
    new_lines.append(FOOTER_LINE + "\n")
    return new_lines, removed_entries, managed_entries


def create_backup(pref_path: Path) -> Path:
    backup_path = pref_path.with_name(pref_path.name + ".back")
    shutil.copy2(pref_path, backup_path)
    return backup_path


def atomic_write(target_path: Path, lines: Iterable[str]) -> None:
    target_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=str(target_path.parent), delete=False) as handle:
        temp_path = Path(handle.name)
        handle.writelines(lines)
    os.replace(temp_path, target_path)


def summarize_entries(entries: Iterable[FavoriteEntry]) -> list[str]:
    return [f"{entry.label} -> {entry.path}" for entry in entries]


def diff_summary(old_entries: list[FavoriteEntry], new_entries: list[FavoriteEntry]) -> tuple[list[str], list[str], list[str]]:
    old_map = {entry.label: entry.path for entry in old_entries}
    new_map = {entry.label: entry.path for entry in new_entries}

    added = [f"{label} -> {new_map[label]}" for label in sorted(new_map.keys() - old_map.keys(), key=str.lower)]
    removed = [f"{label} -> {old_map[label]}" for label in sorted(old_map.keys() - new_map.keys(), key=str.lower)]
    changed = []
    for label in sorted(old_map.keys() & new_map.keys(), key=str.lower):
        if old_map[label] != new_map[label]:
            changed.append(f"{label}: {old_map[label]} -> {new_map[label]}")
    return added, removed, changed


def build_change_rows(old_entries: list[FavoriteEntry], new_entries: list[FavoriteEntry]) -> list[ChangeRow]:
    old_map = {entry.label: entry.path for entry in old_entries}
    new_map = {entry.label: entry.path for entry in new_entries}
    rows: list[ChangeRow] = []

    for label in sorted(new_map.keys() - old_map.keys(), key=str.lower):
        rows.append(ChangeRow("Add", label, "", new_map[label]))

    for label in sorted(old_map.keys() - new_map.keys(), key=str.lower):
        rows.append(ChangeRow("Remove", label, old_map[label], ""))

    for label in sorted(old_map.keys() & new_map.keys(), key=str.lower):
        if old_map[label] != new_map[label]:
            rows.append(ChangeRow("Update", label, old_map[label], new_map[label]))
    for label in sorted(old_map.keys() & new_map.keys(), key=str.lower):
        if old_map[label] == new_map[label]:
            rows.append(ChangeRow("Keep", label, old_map[label], new_map[label]))

    return rows


def ensure_paths_exist(config: PlatformConfig) -> None:
    missing = []
    if not config.desktop_path.exists():
        missing.append(f"No existe Desktop: {config.desktop_path}")
    if not config.t_root_path.exists():
        missing.append(f"No existe la raiz T: {config.t_root_path}")
    if missing:
        raise FileNotFoundError("\n".join(missing))


def execute_update(pref_path: Path, platform_name: str | None = None, dry_run: bool = False):
    config = detect_platform_config(platform_name)
    ensure_paths_exist(config)
    new_lines, current_entries, new_entries = build_updated_lines(pref_path, config)
    added, removed, changed = diff_summary(current_entries, new_entries)

    backup_path = None
    if not dry_run:
        if pref_path.exists():
            backup_path = create_backup(pref_path)
        atomic_write(pref_path, new_lines)

    return config, current_entries, new_entries, added, removed, changed, backup_path


def show_ui(platform_name: str | None = None) -> int:
    pref_path = Path.home() / ".nuke" / PREF_FILENAME
    try:
        config = detect_platform_config(platform_name)
        ensure_paths_exist(config)
        _, current_entries, new_entries = build_updated_lines(pref_path, config)
    except Exception as exc:
        if nuke:
            nuke.message(f"Update Folder Favs\n\n{exc}")
        else:
            print(f"ERROR: {exc}")
        return 1

    rows = build_change_rows(current_entries, new_entries)
    window = UpdateFolderFavsWindow(config, rows, current_entries, new_entries, pref_path)
    window.setAttribute(Qt.WA_DeleteOnClose)
    window.show()

    global update_folder_favs_window
    update_folder_favs_window = window
    return 0


def main(dry_run: bool = False, platform_name: str | None = None) -> int:
    pref_path = Path.home() / ".nuke" / PREF_FILENAME
    if dry_run or not nuke:
        try:
            config = detect_platform_config(platform_name)
            ensure_paths_exist(config)
            _, current_entries, new_entries = build_updated_lines(pref_path, config)
            rows = build_change_rows(current_entries, new_entries)
        except Exception as exc:
            print(f"ERROR: {exc}")
            return 1

        print(f"Sistema detectado: {config.name}")
        print(f"Desktop: {config.desktop_path}")
        print(f"T: {config.t_root_path}")
        print(f"Backup: {pref_path}.back")
        print("")
        if rows:
            for row in rows:
                print(f"{row.action}: {row.name} | {row.current_path or '-'} | {row.new_path or '-'}")
        else:
            print("No hay cambios.")
        return 0

    return show_ui(platform_name=platform_name)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Actualiza favoritos de carpetas para Nuke/Hiero.")
    parser.add_argument("--platform", choices=("windows", "mac"), help="Fuerza plataforma para pruebas.")
    parser.add_argument("--dry-run", action="store_true", help="Muestra cambios por consola sin escribir.")
    return parser


def cli(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    return main(dry_run=args.dry_run, platform_name=args.platform)


if __name__ == "__main__":
    raise SystemExit(cli())
