"""
_____________________________________________________

  LGA_UpdateFolderFavs v1.00 | Lega
  Actualiza las carpetas favoritas del file browser 
  de Nuke/Hiero según la plataforma detectada.
_____________________________________________________

"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import shlex
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import nuke  # type: ignore
except ImportError:
    nuke = None


PREF_FILENAME = "FileChooser_Favorites.pref"
HEADER_LINE = "# Do not edit this file, it is automatically generated by NukeStudio."
FOOTER_LINE = "# End of generated file."
MANAGED_FLAGS = (
    "-image",
    "-script",
    "-project",
    "-python",
    "-font",
    "-geo",
    "-misc",
    "-sequence",
)


@dataclass(frozen=True)
class FavoriteEntry:
    flags: tuple[str, ...]
    label: str
    display_label: str
    shortcut: str
    path: str
    raw_line: str


@dataclass(frozen=True)
class PlatformConfig:
    name: str
    desktop_path: Path
    t_root_path: Path


def detect_platform_config(platform_name: str | None = None) -> PlatformConfig:
    system_name = (platform_name or platform.system()).lower()
    home = Path.home()

    if system_name.startswith("win"):
        return PlatformConfig(
            name="windows",
            desktop_path=home / "Desktop",
            t_root_path=Path("T:/"),
        )

    if system_name in {"darwin", "mac", "macos"}:
        return PlatformConfig(
            name="mac",
            desktop_path=home / "Desktop",
            t_root_path=Path("/Volumes/T Viaja/T"),
        )

    raise RuntimeError(f"Sistema no soportado: {platform_name or platform.system()}")


def normalize_path_string(value: str) -> str:
    path = value.strip().strip('"').replace("\\", "/")

    if path.startswith("T:/"):
        prefix = "T:/"
        rest = path[3:]
        while "//" in rest:
            rest = rest.replace("//", "/")
        if rest.endswith("/") and rest != "/":
            rest = rest.rstrip("/")
        return prefix + rest

    while "//" in path:
        path = path.replace("//", "/")
    if path.endswith("/") and path != "/":
        path = path.rstrip("/")
    return path


def render_token(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def favorite_line(entry: FavoriteEntry) -> str:
    parts = ["add_favorite_dir"]
    parts.extend(entry.flags)
    parts.append(render_token(entry.label))
    parts.append(render_token(entry.display_label))
    parts.append(render_token(entry.shortcut))
    parts.append(render_token(entry.path))
    return " ".join(parts)


def parse_favorite_line(line: str) -> FavoriteEntry | None:
    stripped = line.strip()
    if not stripped.startswith("add_favorite_dir "):
        return None

    try:
        tokens = shlex.split(stripped, posix=True)
    except ValueError:
        return None

    if len(tokens) < 5 or tokens[0] != "add_favorite_dir":
        return None

    payload = tokens[1:]
    index = 0
    flags: list[str] = []
    while index < len(payload) and payload[index].startswith("-"):
        flags.append(payload[index])
        index += 1

    if len(payload) - index < 4:
        return None

    label, display_label, shortcut, path = payload[index : index + 4]
    return FavoriteEntry(
        flags=tuple(flags),
        label=label,
        display_label=display_label,
        shortcut=shortcut,
        path=normalize_path_string(path),
        raw_line=line.rstrip("\n"),
    )


def build_managed_entries(config: PlatformConfig) -> list[FavoriteEntry]:
    entries = [
        FavoriteEntry(
            flags=MANAGED_FLAGS,
            label="Desktop",
            display_label="Desktop",
            shortcut="",
            path=normalize_path_string(str(config.desktop_path)),
            raw_line="",
        ),
        FavoriteEntry(
            flags=MANAGED_FLAGS,
            label="T:",
            display_label="T:",
            shortcut="",
            path=normalize_path_string(str(config.t_root_path)),
            raw_line="",
        ),
    ]

    vfx_names = sorted(
        [
            child.name
            for child in config.t_root_path.iterdir()
            if child.is_dir() and child.name.startswith("VFX-")
        ],
        key=str.lower,
    )

    for name in vfx_names:
        entries.append(
            FavoriteEntry(
                flags=MANAGED_FLAGS,
                label=name,
                display_label=name,
                shortcut="",
                path=normalize_path_string(str(config.t_root_path / name)),
                raw_line="",
            )
        )

    return entries


def managed_roots(config: PlatformConfig) -> tuple[str, str]:
    desktop = normalize_path_string(str(config.desktop_path))
    t_root = normalize_path_string(str(config.t_root_path))
    return desktop, t_root


def is_managed_entry(entry: FavoriteEntry, config: PlatformConfig) -> bool:
    desktop, t_root = managed_roots(config)
    entry_path = normalize_path_string(entry.path)

    if entry.label in {"Desktop", "Desktop Mac"} or entry_path == desktop:
        return True

    if entry.label in {"T:", "T", "T Mac"} or entry_path == t_root:
        return True

    if entry.label.startswith("VFX-"):
        return True

    if entry_path.startswith(t_root + "/") and Path(entry_path).name.startswith("VFX-"):
        return True

    if entry_path.startswith("/../Volumes/") and Path(entry_path).name.startswith("VFX-"):
        return True

    return False


def read_pref_lines(pref_path: Path) -> list[str]:
    if not pref_path.exists():
        return [HEADER_LINE + "\n", "\n", FOOTER_LINE + "\n"]
    return pref_path.read_text(encoding="utf-8").splitlines(keepends=True)


def build_updated_lines(
    pref_path: Path, config: PlatformConfig
) -> tuple[list[str], list[FavoriteEntry], list[FavoriteEntry]]:
    original_lines = read_pref_lines(pref_path)
    kept_lines: list[str] = []
    removed_entries: list[FavoriteEntry] = []

    for line in original_lines:
        entry = parse_favorite_line(line)
        if entry and is_managed_entry(entry, config):
            removed_entries.append(entry)
            continue
        kept_lines.append(line)

    managed_entries = build_managed_entries(config)
    generated_lines = [favorite_line(entry) + "\n" for entry in managed_entries]

    header_lines = [line for line in kept_lines if line.startswith("#")]
    other_lines = [line for line in kept_lines if not line.startswith("#")]

    has_header = any(line.strip() == HEADER_LINE for line in header_lines)
    new_lines: list[str] = []

    if has_header:
        for line in header_lines:
            if line.strip() != FOOTER_LINE:
                new_lines.append(line)
    else:
        new_lines.append(HEADER_LINE + "\n")
        new_lines.append("\n")

    if other_lines:
        new_lines.extend(other_lines)
        if new_lines[-1].strip():
            new_lines.append("\n")

    new_lines.extend(generated_lines)
    if new_lines[-1].strip():
        new_lines.append("\n")
    new_lines.append(FOOTER_LINE + "\n")

    return new_lines, removed_entries, managed_entries


def create_backup(pref_path: Path) -> Path:
    backup_path = pref_path.with_name(pref_path.name + ".back")
    shutil.copy2(pref_path, backup_path)
    return backup_path


def atomic_write(target_path: Path, lines: Iterable[str]) -> None:
    target_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=str(target_path.parent),
        delete=False,
    ) as handle:
        temp_path = Path(handle.name)
        handle.writelines(lines)

    os.replace(temp_path, target_path)


def summarize_entries(entries: Iterable[FavoriteEntry]) -> list[str]:
    return [f"{entry.label} -> {entry.path}" for entry in entries]


def diff_summary(
    old_entries: list[FavoriteEntry], new_entries: list[FavoriteEntry]
) -> tuple[list[str], list[str], list[str]]:
    old_map = {entry.label: entry.path for entry in old_entries}
    new_map = {entry.label: entry.path for entry in new_entries}

    added = [
        f"{label} -> {new_map[label]}"
        for label in sorted(new_map.keys() - old_map.keys(), key=str.lower)
    ]
    removed = [
        f"{label} -> {old_map[label]}"
        for label in sorted(old_map.keys() - new_map.keys(), key=str.lower)
    ]

    changed = []
    for label in sorted(old_map.keys() & new_map.keys(), key=str.lower):
        if old_map[label] != new_map[label]:
            changed.append(f"{label}: {old_map[label]} -> {new_map[label]}")

    return added, removed, changed


def ensure_paths_exist(config: PlatformConfig) -> None:
    missing = []
    if not config.desktop_path.exists():
        missing.append(f"No existe Desktop: {config.desktop_path}")
    if not config.t_root_path.exists():
        missing.append(f"No existe la raiz T: {config.t_root_path}")

    if missing:
        raise FileNotFoundError("\n".join(missing))


def build_preview_message(
    config: PlatformConfig,
    current_entries: list[FavoriteEntry],
    new_entries: list[FavoriteEntry],
    added: list[str],
    removed: list[str],
    changed: list[str],
) -> str:
    lines = [
        f"Sistema detectado: {config.name}",
        f"Desktop: {config.desktop_path}",
        f"T: {config.t_root_path}",
        "",
        "Favoritos actuales administrados:",
    ]

    current_summary = summarize_entries(current_entries)
    if current_summary:
        lines.extend(current_summary)
    else:
        lines.append("<ninguno>")

    lines.extend(["", "Favoritos nuevos:"])
    lines.extend(summarize_entries(new_entries))

    lines.extend(["", "Cambios a aplicar:"])
    if added:
        lines.append("Agregar:")
        lines.extend(added)
    if removed:
        lines.append("Eliminar:")
        lines.extend(removed)
    if changed:
        lines.append("Modificar:")
        lines.extend(changed)
    if not any((added, removed, changed)):
        lines.append("No hay cambios.")

    lines.extend(
        [
            "",
            "Se va a crear/actualizar un backup .back antes de escribir.",
            "",
            "¿Aplicar cambios?",
        ]
    )
    return "\n".join(lines)


def show_message(message: str) -> None:
    if nuke:
        nuke.message(message)
    else:
        print(message)


def ask_confirmation(message: str) -> bool:
    if nuke:
        return nuke.ask(message)
    print(message)
    return False


def execute_update(
    pref_path: Path, platform_name: str | None = None, dry_run: bool = False
) -> tuple[
    PlatformConfig,
    list[FavoriteEntry],
    list[FavoriteEntry],
    list[str],
    list[str],
    list[str],
    Path | None,
]:
    config = detect_platform_config(platform_name)
    ensure_paths_exist(config)

    new_lines, current_entries, new_entries = build_updated_lines(pref_path, config)
    added, removed, changed = diff_summary(current_entries, new_entries)

    backup_path = None
    if not dry_run:
        if pref_path.exists():
            backup_path = create_backup(pref_path)
        atomic_write(pref_path, new_lines)

    return config, current_entries, new_entries, added, removed, changed, backup_path


def main(dry_run: bool = False, platform_name: str | None = None) -> int:
    pref_path = Path.home() / ".nuke" / PREF_FILENAME

    try:
        config = detect_platform_config(platform_name)
        ensure_paths_exist(config)
        _, current_entries, new_entries = build_updated_lines(pref_path, config)
        added, removed, changed = diff_summary(current_entries, new_entries)
    except Exception as exc:
        show_message(f"Update Folder Favs\n\n{exc}")
        return 1

    preview = build_preview_message(
        config=config,
        current_entries=current_entries,
        new_entries=new_entries,
        added=added,
        removed=removed,
        changed=changed,
    )

    if dry_run or not nuke:
        print(preview)
        return 0 if dry_run else 1

    if not ask_confirmation(preview):
        return 0

    try:
        _, _, final_entries, added, removed, changed, backup_path = execute_update(
            pref_path=pref_path,
            platform_name=platform_name,
            dry_run=False,
        )
    except Exception as exc:
        show_message(f"Update Folder Favs\n\nNo se pudieron aplicar los cambios:\n{exc}")
        return 1

    result_lines = ["Update Folder Favs", "", "Favoritos actualizados correctamente."]
    if backup_path:
        result_lines.extend(["", f"Backup: {backup_path}"])
    result_lines.extend(["", "Favoritos finales:"])
    result_lines.extend(summarize_entries(final_entries))

    if not any((added, removed, changed)):
        result_lines.extend(["", "No había cambios, pero el archivo fue normalizado."])

    show_message("\n".join(result_lines))
    return 0


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Actualiza favoritos de carpetas para Nuke/Hiero.")
    parser.add_argument(
        "--platform",
        choices=("windows", "mac"),
        help="Fuerza plataforma para pruebas fuera de Nuke.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Muestra el preview sin escribir el archivo.",
    )
    return parser


def cli(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    return main(dry_run=args.dry_run, platform_name=args.platform)


if __name__ == "__main__":
    raise SystemExit(cli())
